/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author beuno
 */

import javax.swing.table.DefaultTableModel;
import model.*;
import service.JogadorService;

public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());
    private JogadorService service = new JogadorService();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal()  {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JLabel();
        txtIdade = new javax.swing.JLabel();
        txtAltura = new javax.swing.JLabel();
        txtRebotes = new javax.swing.JLabel();
        txtPontos = new javax.swing.JLabel();
        txtPosição = new javax.swing.JLabel();
        jtextNOME = new javax.swing.JTextField();
        jtextIdade = new javax.swing.JTextField();
        jtextRebotes = new javax.swing.JTextField();
        jtextPontos = new javax.swing.JTextField();
        jtextAltura = new javax.swing.JTextField();
        cmbPosicao = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        bntLimpar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJogadores = new javax.swing.JTable();
        txtAssistencias = new javax.swing.JLabel();
        jtextAssistencias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNome.setText("Nome");

        txtIdade.setText("Idade");

        txtAltura.setText("Altura");

        txtRebotes.setText("Rebotes");

        txtPontos.setText("Pontos");

        txtPosição.setText("Posição");

        jtextNOME.addActionListener(this::jtextNOMEActionPerformed);

        jtextIdade.addActionListener(this::jtextIdadeActionPerformed);

        jtextRebotes.addActionListener(this::jtextRebotesActionPerformed);

        jtextPontos.addActionListener(this::jtextPontosActionPerformed);

        jtextAltura.addActionListener(this::jtextAlturaActionPerformed);

        cmbPosicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Armador", "Ala", "Pivo", "Ala-Armador", "Ala-Pivo" }));
        cmbPosicao.addActionListener(this::cmbPosicaoActionPerformed);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        bntLimpar.setText("Limpar");
        bntLimpar.addActionListener(this::bntLimparActionPerformed);

        bntExcluir.setText("Excluir");
        bntExcluir.addActionListener(this::bntExcluirActionPerformed);

        tblJogadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Posição", "Pontos", "Rebotes", "Assistencias", "Desempenho"
            }
        ));
        jScrollPane1.setViewportView(tblJogadores);

        txtAssistencias.setText("Assistências");

        jtextAssistencias.addActionListener(this::jtextAssistenciasActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText(" SCOUT BASKET MANAGER");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setText("Sistema de Gerenciamento de Atletas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPosição)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdade)
                            .addComponent(txtNome))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(bntLimpar)
                        .addGap(42, 42, 42)
                        .addComponent(btnCadastrar)
                        .addGap(48, 48, 48)
                        .addComponent(bntExcluir))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPontos)
                            .addComponent(txtRebotes)
                            .addComponent(txtAltura)
                            .addComponent(txtAssistencias))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jtextRebotes, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtextAssistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome)
                    .addComponent(jtextNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPosição, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdade)
                    .addComponent(jtextIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPontos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextPontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRebotes)
                    .addComponent(jtextRebotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCadastrar)
                                .addComponent(bntExcluir))
                            .addComponent(bntLimpar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtextAssistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAssistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextNOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNOMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNOMEActionPerformed

    private void jtextIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextIdadeActionPerformed

    private void jtextRebotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextRebotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextRebotesActionPerformed

    private void jtextPontosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextPontosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextPontosActionPerformed

    private void jtextAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextAlturaActionPerformed

    private void cmbPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPosicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPosicaoActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    try {
    String nome = jtextNOME.getText();
    int idade = Integer.parseInt(jtextIdade.getText());
    double altura = Double.parseDouble(jtextAltura.getText());

    int pontos = Integer.parseInt(jtextPontos.getText());
    int rebotes = Integer.parseInt(jtextRebotes.getText());
    int assistencias = Integer.parseInt(jtextAssistencias.getText());

    String posicao = cmbPosicao.getSelectedItem().toString();

    jogador jogador;

    if (posicao.equals("Armador")) {
        jogador = new Armador(nome, idade, altura, pontos, rebotes, assistencias);
        
    } else if (posicao.equals("Ala")) {
        jogador = new Ala(nome, idade, altura, pontos, rebotes, assistencias);
        
    } else if (posicao.equals("Ala-Armador")) {
        jogador = new AlaArmador(nome, idade, altura, pontos, rebotes, assistencias);
        
    }else if (posicao.equals("Ala-Pivo")) {
        jogador = new AlaPivo(nome, idade, altura, pontos, rebotes, assistencias);
    }
    else {
        jogador = new Pivo(nome, idade, altura, pontos, rebotes, assistencias);
    }

    service.adicionarJogador(jogador);

    DefaultTableModel modelo = (DefaultTableModel) tblJogadores.getModel();

    modelo.addRow(new Object[]{
    jogador.getNome(),
    posicao,
    jogador.getPontos(),
    jogador.getRebotes(),
    jogador.getAssistencias(),
    jogador.calculateDesempenho()
});

    javax.swing.JOptionPane.showMessageDialog(this, "Jogador cadastrado com sucesso! \n\n"
    + jogador.mostrarFuncao());

    jtextNOME.setText("");
    jtextIdade.setText("");
    jtextAltura.setText("");
    jtextPontos.setText("");
    jtextRebotes.setText("");
    jtextAssistencias.setText("");
    cmbPosicao.setSelectedIndex(0);

} catch (NumberFormatException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Preencha os campos numéricos corretamente.");
}

             // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void bntLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLimparActionPerformed
        jtextNOME.setText("");
        jtextIdade.setText("");
        jtextAltura.setText("");
        jtextPontos.setText("");
        jtextRebotes.setText("");
        jtextAssistencias.setText("");

        cmbPosicao.setSelectedIndex(0);
        jtextNOME.requestFocus();
    }//GEN-LAST:event_bntLimparActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tblJogadores.getModel();

        int linhaSelecionada = tblJogadores.getSelectedRow();

        if (linhaSelecionada != -1) {
            modelo.removeRow(linhaSelecionada);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um jogador para excluir.");
        }
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void jtextAssistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextAssistenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextAssistenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntExcluir;
    private javax.swing.JButton bntLimpar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JComboBox<String> cmbPosicao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtextAltura;
    private javax.swing.JTextField jtextAssistencias;
    private javax.swing.JTextField jtextIdade;
    private javax.swing.JTextField jtextNOME;
    private javax.swing.JTextField jtextPontos;
    private javax.swing.JTextField jtextRebotes;
    private javax.swing.JTable tblJogadores;
    private javax.swing.JLabel txtAltura;
    private javax.swing.JLabel txtAssistencias;
    private javax.swing.JLabel txtIdade;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtPontos;
    private javax.swing.JLabel txtPosição;
    private javax.swing.JLabel txtRebotes;
    // End of variables declaration//GEN-END:variables
}
